apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: will42
  name: will42
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will42
  template:
    metadata:
      labels:
        app: will42
    spec:
      containers:
      - image: nginx
        name: will42
        # ports:
        # - containerPort: 80
