NODE_SERVER_NAME = "mfouadiSyt"
NODE_SERVER_IP = '192.168.56.110'
HOME_DIRECTORY = '/home/vagrant'

Vagrant.configure("2") do |config|
  # config.vm.box = "bento/centos-stream-10"
  # config.vm.box_version = "202510.26.0"
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vm|
    vm.name = NODE_SERVER_NAME
    vm.customize ["modifyvm", :id, "--name", NODE_SERVER_NAME]
  end

  config.vm.define NODE_SERVER_NAME do |node|
    node.vm.hostname = NODE_SERVER_NAME
    node.vm.network "private_network", ip: NODE_SERVER_IP
    node.vm.synced_folder ".", "/vagrant", disabled: true
    node.vm.provider "virtualbox" do |v|
      v.name = NODE_SERVER_NAME
      v.memory = 2048
      v.cpus = 2
    end
  end
  
  config.vm.provision "shell",
    name: "init environement...",
    env: {
      "NODE_SERVER_IP" => NODE_SERVER_IP,
      "HOME_DIRECTORY" => HOME_DIRECTORY
    },
    path: "./scripts/init.sh" 

  config.vm.provision "shell",
    name: "Deploy apps and services...",
    env: {
      "NODE_SERVER_IP" => NODE_SERVER_IP,
      "HOME_DIRECTORY" => HOME_DIRECTORY
    },
    path: "./scripts/deploy.sh" 

end