def load_env(file_path)
  if File.exist?(file_path)
    File.readlines(file_path).each do |line|
      key, value = line.strip.split('=', 2)
      ENV[key.strip] = value.strip if key && value
    end
  end
end

load_env('../.env')

SERVICES = {
  "mfouadiS" => {
    ip: ENV['SERVER_NODE_IP']
  }
}

# puts ENV['SERVER_NODE_IP'], '<-- ENV --', SERVICES['mfouadiS'][:ip], '<-- SERVICES --'

Vagrant.configure("2") do |config|
  config.vm.hostname = "mfouadiS"
  config.vm.box = "ubuntu_24_server"
  
  config.vm.provider "virtualbox" do |vm|
    vm.name = "mfouadiS"
    vm.customize ["modifyvm", :id, "--name", "mfouadiS"]
    vm.cpus = 1
end
    vm.memory = 512
  end

  config.vm.network "forwarded_port", guest: 8001, host: 8001

  config.vm.network "private_network", ip: SERVICES['mfouadiS'][:ip] 

  config.vm.provision "shell",
    name: "init-environment",
    path: "./scripts/init.sh"
end