load 'vars.rb'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream10"
  config.vm.box_version = "20251020.0"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vm|
    vm.name = NODE_SERVER_NAME
    vm.customize ["modifyvm", :id, "--name", NODE_SERVER_NAME]
  end

  config.vm.define NODE_SERVER_NAME do |node|
    node.vm.hostname = NODE_SERVER_NAME
    node.vm.network "private_network", ip: NODE_SERVER_IP
    node.vm.synced_folder ".", "/vagrant", disabled: true
    node.vm.provider "virtualbox" do |v|
      v.name = NODE_SERVER_NAME
      v.memory = 2048
      v.cpus = 2
    end
  end
  
  config.vm.provision "shell",
    name: "init environement",
    env: {
      "NODE_SERVER_IP" => NODE_SERVER_IP,
      "HOME_DIRECTORY" => HOME_DIRECTORY
    },
    path: "./scripts/init.sh" 

end